# Generated by Django 4.2.5 on 2023-10-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_table_relevant_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='part_name',
            field=models.TextField(max_length=100),
        ),
    ]
