# Generated by Django 4.2.5 on 2023-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0003_alter_table_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='relevant_informations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
