# Generated by Django 4.2.5 on 2024-05-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0004_alter_table_code_alter_table_relevant_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='part_name',
            field=models.TextField(blank=True, default='default_part', max_length=100, null=True),
        ),
    ]
